liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: images/cache


    #    # define your filter sets under this option
    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        my_thumbnail:
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
            quality : 75
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [340, 450]
                    mode:          outbound
                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
